// lib/v-wang-editor/VWangEditor.jsx
import E from 'wangeditor'

const VWangEditor = {
  name: 'VWangEditor',
  model: {
    prop: 'value',
    event: 'update:value'
  },
  props: {
    value: String,
    config: {
      type: Object,
      default: () => ({})
    }
  },
  data() {
    return {
      editor: null,
      content: this.value
    }
  },
  watch: {
    value(val) {
      if (val !== this.content) {
        this.editor.txt.html(val)
      }
    },
    content(val) {
      this.$emit('update:value', val)
    }
  },
  mounted() {
    const editor = new E(this.$refs.editor)

    editor.config.onchange = (html) => {
      this.content = html
    }

    editor.config = Object.assign(editor.config, this.config)

    editor.create()

    this.editor = editor

    this.editor.txt.html(this.content)
  },
  beforeDestroy() {
    this.editor.destroy()
    this.editor = null
  },
  render() {
    return <div ref="editor"/>
  },
}

export default VWangEditor

// lib/components/VWangEditor/VWangEditor.vue
<template>
  <div ref="editor"></div>
</template>

<script>
  import E from 'wangeditor'

  export default {
    name: 'VWangEditor',
    model: {
      prop: 'value',
      event: 'update:value'
    },
    props: {
      value: String,
      config: {
        type: Object,
        default: () => ({})
      }
    },
    watch: {
      value(val) {
        if (val !== this.content) {
          this.editor.txt.html(val)
        }
      },
      content(val) {
        this.$emit('update:value', val)
      }
    },
    data() {
      return {
        editor: null,
        content: this.value
      }
    },
    mounted() {
      const editor = new E(this.$refs.editor)

      editor.config.onchange = (html) => {
        this.content = html
      }

      editor.config = Object.assign(editor.config, this.config)

      editor.create()

      this.editor = editor

      this.editor.txt.html(this.content)
    },
    beforeDestroy() {
      this.editor.destroy()
      this.editor = null
    }
  }
</script>
