// lib/components/VExcelExport/VExcelExport.vue
<template>
  <el-button
    v-loading.fullscreen.lock="loading"
    :element-loading-text="loadingText"
    v-bind="$attrs"
    @click="handleDownload"
  >
    <slot>导出</slot>
  </el-button>
</template>

<script>
  // utils
  import parseTime from 'lib/utils/parse-time'

  export default {
    name: 'VExcelExport',
    props: {
      canExport: Boolean,
      loadingText: {
        type: String,
        default: '正在导出所有需要发货的维修单（所有发行方）...'
      },
      tHeader: {
        type: Array,
        default: () => []
      },
      tBody: {
        type: Array,
        default: () => []
      },
      filename: String
    },
    data() {
      return {
        loading: false
      }
    },
    methods: {
      handleDownload() {
        if (this.canExport) {
          this.loading = true
          import('lib/vendor/Export2Excel').then(excel => {
            const tHeader = this.tHeader
            const tBody = this.tBody
            excel.export_json_to_excel({
              header: tHeader,
              data: tBody,
              filename: this.filename + '_' + parseTime(new Date(), '{y}{m}{d}')
            })
            this.loading = false
          })
        } else {
          this.$message.warning('数据加载中...')
        }
      }
    }
  }
</script>

// lib/components/VExcelExport/VExcelExport.jsx
const VExcelExport = {
  name: 'VExcelExport',
  props: {
    canExport: Boolean,
    loadingText: {
      type: String,
      default: '正在导出数据...'
    },
    tHeader: {
      type: Array,
      default: () => []
    },
    tBody: {
      type: Array,
      default: () => []
    },
    filename: String
  },
  data() {
    return {
      loading: false
    }
  },
  methods: {
    handleDownload() {
      if (this.canExport) {
        this.loading = true
        import('lib/vendor/Export2Excel').then(excel => {
          const tHeader = this.tHeader
          const tBody = this.tBody
          excel.export_json_to_excel({
            header: tHeader,
            data: tBody,
            filename: this.filename + '_' + this.$D(new Date()).format('YYYY-MM-DD HH:mm:ss')
          })
          this.loading = false
        })
      } else {
        this.$message.warning('数据准备中...')
      }
    }
  },
  render() {
    const { loading, loadingText, handleDownload, $slots } = this

    const data = {
      props: {
        ...this.$attrs
      },
    }

    return (
      <el-button
        {...data}
        vLoading_fullscreen_lock={loading}
        element-loading-text={loadingText}
        onClick={handleDownload}
      >
        {$slots.default || '上传'}
      </el-button>
    )
  }
}

export default VExcelExport
