// examples/views/vradio/index.vue
<template>
  <demo-wrapper title="VRadio 单选框">
    <demo-card title="basic">
      <v-radio v-model="value" :options="options"/>
    </demo-card>
    <demo-card title="border">
      <v-radio v-model="value" :options="options" border/>
    </demo-card>
    <demo-card title="button">
      <v-radio v-model="value" :options="options" button/>
    </demo-card>
    <demo-card title="disabled">
      <v-radio v-model="value" :options="options" button disabled/>
    </demo-card>
    <README/>
  </demo-wrapper>
</template>

<script>
import README from './README.md'

export default {
  name: 'vradio',
  data() {
    return {
      value: 1,
      options: [
        { label: '上海', value: 1 },
        { label: '北京', value: 2, disabled: true },
        { label: '广州', value: 3 },
        { label: '深圳', value: 4 },
      ]
    }
  },
  components: {
    README
  }
}
</script>

<style>

</style>

// lib/v-radio/v-radio.jsx
const VRadio = {
  name: 'VRadio',
  model: {
    prop: 'value',
    event: 'input'
  },
  props: {
    value: [String, Number, Boolean],
    options: {
      type: Array,
      default: () => [],
      required: true
    },
    button: {
      type: Boolean,
      default: false
    },
    border: {
      type: Boolean,
      default: false
    },
    prop: {
      type: Object,
      default: () => ({ label: 'label', value: 'value' })
    }
  },
  computed: {
    _options() {
      return Array.from(this.options).map((item) => ({
        ...item,
        text: item[this.prop.label],
        value: item[this.prop.value],
      }))
    }
  },
  render() {
    const data = {
      attrs: {
        ...this.$attrs,
      },
      on: {
        ...this.$listeners,
      },
    }

    const renderButton = (props) => {
      return <el-radio-button label={props.value} disabled={props.disabled}>{props.label}</el-radio-button>
    }

    const renderRadio = (props) => {
      return <el-radio label={props.value} border={this.border} disabled={props.disabled}>{props.label}</el-radio>
    }

    return (
      <el-radio-group
        {...data}
        value={this.value}
      >
        {this._options.map((item) => this.button ? renderButton(item) : renderRadio(item))}
      </el-radio-group>
    )
  }
}

export default VRadio
